apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-kustomize
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/dev
    repoURL: git@github.com:nunucloud/kustomize.git
    targetRevision: HEAD